theme: jekyll-theme-minimal
title: Ruming Liu
email: rumingliu1303@gmail.com
linkedin: https://www.linkedin.com/
github:
  is_project_page: false
# title: 你的名字
# affiliation: 你的单位
# email: yourname (at) example.edu
# google_scholar: https://scholar.google.com/
# github_link: https://github.com/yaoyao-liu/minimal-light
# linkedin: https://www.linkedin.com/
# avatar: ./assets/img/avatar.png
# google_analytics: UA-111540567-4
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png
# description: 在这里输入网页描述.
# canonical: https://minimal-light.yyliu.net/
# remote_theme: yaoyao-liu/minimal-light
